spring:
  application:
    name: mnsx_system
  datasource:
    url: jdbc:mysql://mnsx.top:3306/mnsx_system?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123123
  redis:
    host: mnsx.top
    port: 6379
    password: 123123
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
server:
  port: 8080
mybatis:
  type-aliases-package: top.mnsx.mnsx_system.entity
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#mnsx:
#  mybatis:
#    interceptor:
#      enabled: false